version: '3.8'
services:
  app_backend_ruby_312:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "3003:3000"
    environment:
      POSTGRES_PASSWORD: devpass
    networks:
      - app-side-network
    platform: linux/x86_64

  db:
    image: postgres:14.3-alpine
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: devpass
    networks:
      - app-side-network

networks:
  app-side-network:
    external: true
