default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD']%>

development:
  <<: *default
  host: db
  database: app_side_development

staging:
  <<: *default
  database: app_side_staging

production:
  <<: *default
  database: app_side_production